export const postsTypes = {
  GET_RECENT_POSTS: 'GET_RECENT_POSTS',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  RECENT_POSTS_ERROR: 'RECENT_POSTS_ERROR',
  POST_BY_ID_ERROR: 'POST_BY_ID_ERROR',
  SET_LOADING_POSTS: 'SET_LOADING_POSTS',
  SET_LOADING_POST_BY_ID: 'SET_LOADING_POST_BY_ID',
}
